package us.tx.state.dfps.service.permanencyplanningform.controller;

import java.util.Locale;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import us.tx.state.dfps.common.exception.InvalidRequestException;
import us.tx.state.dfps.service.common.request.PpmReq;
import us.tx.state.dfps.service.common.response.CommonFormRes;
import us.tx.state.dfps.service.common.util.TypeConvUtil;
import us.tx.state.dfps.service.permanencyplanningform.Service.PermanencyPlanMeetService;

/**
 * service-business- IMPACT PHASE 2 MODERNIZATION Class Description:Notice of
 * Permanency Planning Team Meeting(English) for form CSC0600 is sent to persons
 * associated with a case. The letter is generated by selecting a row in the
 * persons listbox and pressing the letter PB. The notice is editable but is NOT
 * saved to the database. Feb 10, 2018- 7:29:42 PM © 2017 Texas Department of
 * Family and Protective Services
 */
@RestController
@RequestMapping("/permanencyplanmeeting")
public class PermanencyPlanMeetingController {

	@Autowired
	MessageSource messageSource;

	@Autowired
	PermanencyPlanMeetService permanencyPlanMeetService;

	private static final Logger log = Logger.getLogger(PermanencyPlanMeetingController.class);

	/**
	 * Method Name: getpermanencyplanmeetinfo Method Description:Get the
	 * information for permanency plan meeting info.
	 * 
	 * @param ppmReq
	 * @return CommonFormRes @
	 */
	@RequestMapping(value = "/getpermanencyplanmeetinfo", headers = {
			"Accept=application/json" }, method = RequestMethod.POST)
	public CommonFormRes getpermanencyplanmeetinfo(@RequestBody PpmReq ppmReq) {

		log.debug("Entering method getpermanencyplanmeetinfo in PermanencyPlanMeetingController");
		CommonFormRes commonFormRes = new CommonFormRes();

		if (TypeConvUtil.isNullOrEmpty(ppmReq.getIdPptPart())) {
			throw new InvalidRequestException(messageSource.getMessage("common.idPpt.mandatory", null, Locale.US));
		}
		if (TypeConvUtil.isNullOrEmpty(ppmReq.getIdPptEvent())) {
			throw new InvalidRequestException(messageSource.getMessage("common.idEvent.mandatory", null, Locale.US));
		}
		if (TypeConvUtil.isNullOrEmpty(ppmReq.getIdStage())) {
			throw new InvalidRequestException(messageSource.getMessage("common.idStage.mandatory", null, Locale.US));
		}
		commonFormRes.setPreFillData(
				TypeConvUtil.getXMLFormat(permanencyPlanMeetService.getPermanencyPlanTeamMeeting(ppmReq)));

		log.debug("Exiting method getpermanencyplanmeetinfo in PermanencyPlanMeetingControllerLog");

		return commonFormRes;
	}

}
