export const environment = {
  production: false,
  environmentName: 'test15',
  disableConsole: true,
  idleSessionDuration: 1800,
  apiUrl: 'https://p2test15.dfps.texas.gov/dfps-pageapi-impact',
  impactLoginUrl: 'https://p2test15.dfps.texas.gov/web/customLogout',
  impactP2WebUrl: 'https://p2test15.dfps.texas.gov/web',
  impactRefreshTokenAuth: 'SU1QQUNUUEgzOklNUEFDVC1QSDMtUkVGUkVTSA==',
  formsUrl: 'https://p2test15.dfps.texas.gov/web/document/launch',
  helpUrl: 'https://p2test15.dfps.texas.gov/web/resources/help/index.htm#t=Page_Descriptions/Finance/',
  logApiUrl: '/v1/log/client',
  primaryNavigationUrl: '/v1/navigation/primary',
  secondaryNavigationUrl: '/v1/navigation/secondary/',
  ternaryNavigationUrl: '/v1/navigation/ternary/',
  contextSharingUrl: '/v1/session/',
  userInfoUrl: '/v1/users/info',
  logoutUrl: '/v1/auth/logout',
  refreshTokenUrl: '/v1/auth/refresh-tokens',
  reportServiceUrl: '/v1/reports/launch',
  primaryNavigation: ['financial'],
  secondaryNavigation: ['contract', 'invoice', 'financialsPaymentApproval', 'financialsPaymentHistory',
    'financial-account', 'payments', 'homeSearch', 'serviceArea', 'central-registry-person-search'],
  ternaryNavigation: ['authProvider', 'contract', 'invoice', 'financialAccntSearch', 'financialAccntDetail',
    'financialAccntRegister', 'regionalAccntDetail', 'reconciliation', 'processPayment', 'paymentGroup',
    'injuryDetail', 'safetyPlan', 'dangerIndicators',
    'financialAccntReport', 'home-information', 'placementLog', 'homeHistory', 'paymentInfo', 'home-assessment-addendum-list',
    'servicePackageTab', 'centralRegistryRequestDetail', 'centralRegistryRecordCheckDetail'],
  isMPSEnvironment: false,
  jwtTokenEndpoint: 'https://p2test15.dfps.texas.gov/dfps-security-oauth2/oauth/token',
    enableImpersonation: true,
    config: {
        auth: {
            clientId: '7a35db4c-c97c-4a33-9dcc-1cc145d7147a',
            authority: 'https://login.microsoftonline.com/ef009161-feef-4a55-babf-7df492aa3bc0',
            validateAuthority: true,
            redirectUri: 'https://p2test15.dfps.texas.gov/impact3/',
            postLogoutRedirectUri: 'https://p2test15.dfps.texas.gov/web/login/',
            navigateToLoginRequestUrl: true,
        },
        cache: {
            cacheLocation: 'localStorage',
        },
        scopes: {
            loginRequest: ['openid', 'profile', 'email', 'offline_access'],
        },
    },
};
