export const environment = {
  production: false,
  environmentName: '',
  disableConsole: true,
  idleSessionDuration: 1800,
  apiUrl: 'https://impact2.dfps.state.tx.us/dfps-pageapi-impact',
  impactLoginUrl: 'https://impact2.dfps.state.tx.us/web/login',
  impactP2WebUrl: 'https://impact2.dfps.state.tx.us/web',
  impactRefreshTokenAuth: 'SU1QQUNUUEgzOklNUEFDVC1QSDMtUkVGUkVTSA==',
  formsUrl: 'https://impact2.dfps.state.tx.us/web/document/launch',
  helpUrl: 'https://impact2.dfps.state.tx.us/web/resources/help/index.htm#t=Page_Descriptions/Finance/',
  logApiUrl: '/v1/log/client',
  primaryNavigationUrl: '/v1/navigation/primary',
  secondaryNavigationUrl: '/v1/navigation/secondary/',
  ternaryNavigationUrl: '/v1/navigation/ternary/',
  userInfoUrl: '/v1/users/info',
  logoutUrl: '/v1/auth/logout',
  refreshTokenUrl: '/v1/auth/refresh-tokens',
  reportServiceUrl: '/v1/reports/launch',
  primaryNavigation: ['financial'],
  secondaryNavigation: ['contract', 'invoice', 'financialsPaymentApproval', 'financialsPaymentHistory',
    'financial-account', 'payments', 'homeSearch', 'serviceArea', 'central-registry-person-search',
    'service-level-error'],
  ternaryNavigation: ['authProvider', 'contract', 'invoice', 'financialAccntSearch', 'financialAccntDetail',
    'financialAccntRegister', 'regionalAccntDetail', 'reconciliation', 'processPayment', 'paymentGroup',
    'injuryDetail', 'safetyPlan', 'dangerIndicators',
    'financialAccntReport', 'home-information', 'placementLog', 'homeHistory', 'paymentInfo', 'home-assessment-addendum-list',
    'centralRegistryRequestDetail', 'centralRegistryRecordCheckDetail'],
  isMPSEnvironment: false,
};

