export const environment = {
  production: false,
  environmentName: 'Local',
  disableConsole: true,
  idleSessionDuration: 1800,
  apiUrl: 'http://localhost:8081/dfps-pageapi-impact',
  impactLoginUrl: 'http://localhost:8085/web/customLogout',
  impactP2WebUrl: 'http://localhost:8085/web',
  impactRefreshTokenAuth: 'SU1QQUNUUEgzOklNUEFDVC1QSDMtUkVGUkVTSA==',
  formsUrl: 'http://localhost:8085/web/document/launch',
  helpUrl: 'https://localhost:8085/web/resources/help/index.htm#t=Page_Descriptions/',
  logApiUrl: '/v1/log/client',
  primaryNavigationUrl: '/v1/navigation/primary',
  secondaryNavigationUrl: '/v1/navigation/secondary/',
  ternaryNavigationUrl: '/v1/navigation/ternary/',
  contextSharingUrl: '/v1/session/',
  userInfoUrl: '/v1/users/info',
  logoutUrl: '/v1/auth/logout',
  refreshTokenUrl: '/v1/auth/refresh-tokens',
  reportServiceUrl: '/v1/reports/launch',
  primaryNavigation: ['financial'],
  secondaryNavigation: ['contract', 'invoice', 'financialsPaymentApproval', 'financialsPaymentHistory',
    'financial-account', 'payments', 'homeSearch','serviceArea','Letters', 'central-registry-person-search',
    'service-level-error'],
  ternaryNavigation: ['authProvider', 'contract', 'invoice', 'financialAccntSearch', 'financialAccntDetail',
    'financialAccntRegister', 'regionalAccntDetail', 'reconciliation', 'processPayment', 'paymentGroup', 'injuryDetail', 'safetyPlan', 'dangerIndicators',
    'financialAccntReport', 'home-information', 'placementLog', 'homeHistory', 'paymentInfo', 'home-assessment-addendum-list','servicePackageTab',
    'financialAccntReport', 'home-information', 'placementLog', 'homeHistory', 'paymentInfo', 'home-assessment-addendum-list',
    'centralRegistryRequestDetail', 'centralRegistryRecordCheckDetail',
    'service-level-error', 'kinHomeAssessmentTab', 'adoAssistanceApplication', 'recertificationDetail'],
  isMPSEnvironment: false,
  jwtTokenEndpoint: 'https://p2impbat16.dfps.texas.gov/dfps-security-oauth2/oauth/token',
  enableImpersonation: true,
  config: {
      auth: {
          clientId: '7b1219a6-9cf0-4bb2-b0d3-0c0bd7eb2ee4',
          authority: 'https://login.microsoftonline.com/057119a8-cdc3-47b9-91d4-8bd4e013a246',
          validateAuthority: true,
          redirectUri: 'http://localhost:4200',
          postLogoutRedirectUri: 'https://p2impbat16.dfps.texas.gov/web/login/',
          navigateToLoginRequestUrl: true,
      },
      cache: {
          cacheLocation: 'localStorage',
      },
      scopes: {
          loginRequest: ['openid', 'profile', 'email', 'offline_access'],
      },
  },
};
