export const environment = {
  production: true,
  enableImpersonation: false,
  environmentName: '',
  disableConsole: true,
  idleSessionDuration: 1800,
  apiUrl: 'https://impact2.dfps.texas.gov/dfps-pageapi-impact',
  impactLoginUrl: 'https://impact2.dfps.texas.gov/web/customLogout',
  impactP2WebUrl: 'https://impact2.dfps.texas.gov/web',
  impactRefreshTokenAuth: 'SU1QQUNUUEgzOklNUEFDVC1QSDMtUkVGUkVTSA==',
  formsUrl: 'https://impact2.dfps.texas.gov/web/document/launch',
  helpUrl: 'https://impact2.dfps.texas.gov/web/resources/help/index.htm#t=Page_Descriptions/Finance/',
  logApiUrl: '/v1/log/client',
  primaryNavigationUrl: '/v1/navigation/primary',
  secondaryNavigationUrl: '/v1/navigation/secondary/',
  ternaryNavigationUrl: '/v1/navigation/ternary/',
  userInfoUrl: '/v1/users/info',
  logoutUrl: '/v1/auth/logout',
  refreshTokenUrl: '/v1/auth/refresh-tokens',
  reportServiceUrl: '/v1/reports/launch',
  primaryNavigation: ['financial'],
  secondaryNavigation: ['contract', 'invoice', 'financialsPaymentApproval', 'financialsPaymentHistory',
    'financial-account', 'payments', 'homeSearch', 'serviceArea', 'central-registry-person-search',
    'service-level-error'],
  ternaryNavigation: ['authProvider', 'contract', 'invoice', 'financialAccntSearch', 'financialAccntDetail',
    'financialAccntRegister', 'regionalAccntDetail', 'reconciliation', 'processPayment', 'paymentGroup',
    'injuryDetail', 'safetyPlan', 'dangerIndicators',
    'financialAccntReport', 'home-information', 'placementLog', 'homeHistory', 'paymentInfo', 'home-assessment-addendum-list','servicePackageTab',
    'centralRegistryRequestDetail', 'centralRegistryRecordCheckDetail', 'kinHomeAssessmentTab'],
  isMPSEnvironment: false,
  jwtTokenEndpoint: 'https://impact2.dfps.texas.gov/dfps-security-oauth2/oauth/token',
    config: {
        auth: {
            clientId: 'f6398cfd-cb89-4c0b-a87d-5cadc6148044',
            authority: 'https://login.microsoftonline.com/0915ef38-12cd-4561-ab80-9c7f41bfb31e',
            validateAuthority: true,
            redirectUri: 'https://impact2.dfps.texas.gov/impact3/',
            postLogoutRedirectUri: 'https://impact2.dfps.texas.gov/web/login/',
            navigateToLoginRequestUrl: true,
        },
        cache: {
            cacheLocation: 'localStorage',
        },
        scopes: {
            loginRequest: ['openid', 'profile', 'email', 'offline_access'],
        },
    },

};
