export const environment = {
  production: true,
  environmentName: 'MPS',
  disableConsole: true,
  idleSessionDuration: 1800,
  apiUrl: 'http://localhost:8080/dfps-pageapi-impact',
  impactLoginUrl: 'http://localhost:8080/web/login',
  impactP2WebUrl: 'http://localhost:8080/web',
  impactRefreshTokenAuth: 'SU1QQUNUUEgzOklNUEFDVC1QSDMtUkVGUkVTSA==',
  formsUrl: 'http://localhost:8080/web/document/launch',
  helpUrl: 'https://localhost:8080/web/resources/help/index.htm#t=Page_Descriptions/Finance/',
  logApiUrl: '/v1/log/client',
  primaryNavigationUrl: '/v1/navigation/primary',
  secondaryNavigationUrl: '/v1/navigation/secondary/',
  ternaryNavigationUrl: '/v1/navigation/ternary/',
  contextSharingUrl: '/v1/session/',
  userInfoUrl: '/v1/users/info',
  logoutUrl: '/v1/auth/logout',
  refreshTokenUrl: '/v1/auth/refresh-tokens',
  reportServiceUrl: '/v1/reports/launch',
  primaryNavigation: ['financial'],
  secondaryNavigation: ['contract', 'invoice', 'financialsPaymentApproval', 'financialsPaymentHistory',
    'financialAccount', 'payments', 'homeSearch','serviceArea', 'central-registry-person-search',
    'service-level-error'],
  ternaryNavigation: ['authProvider', 'invoice', 'financialAccntSearch', 'financialAccntDetail',
    'financialAccntRegister', 'regionalAccntDetail', 'reconciliation', 'processPayment', 'paymentGroup',
    'financialAccntReport', 'home-information', 'placementLog', 'homeHistory', 'paymentInfo', 'home-assessment-addendum-list',
    'centralRegistryRequestDetail', 'centralRegistryRecordCheckDetail', 'kinHomeAssessmentTab'],
  isMPSEnvironment: true,
  jwtTokenEndpoint: 'https://p2test15.dfps.texas.gov/dfps-security-oauth2/oauth/token',
    enableImpersonation: true,
    config: {
        auth: {
            clientId: '7a35db4c-c97c-4a33-9dcc-1cc145d7147a',
            authority: 'https://login.microsoftonline.com/ef009161-feef-4a55-babf-7df492aa3bc0',
            validateAuthority: true,
            redirectUri: 'http://localhost:8080/impact3/',
            postLogoutRedirectUri: 'http://localhost:8080/web/login/',
            navigateToLoginRequestUrl: true,
        },
        cache: {
            cacheLocation: 'localStorage',
        },
        scopes: {
            loginRequest: ['openid', 'profile', 'email', 'offline_access'],
        },
    }
};
